name: RPM Build centos7
on:
    push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Package RPM and SRPM
      uses: guilbaults/rpm-package-action@centos
      with:
        path: .
        spec: slurm-job-exporter-el7.spec
        distro: centos-7

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Centos 7 binary RPM
        path: output/*.noarch.rpm
